apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: associazione-api-staging

bases:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml

images:
  - name: ghcr.io/DevilFlow92/associazione-api
    newTag: staging