apiVersion: v1
kind: Secret
metadata:
  name: {{ include "associazione-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "associazione-api.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  DATABASE_URL: {{ .Values.secret.databaseUrl | b64enc | quote }}
  SECRET_KEY: {{ .Values.secret.secretKey | b64enc | quote }}