apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: associazione-api-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: dev

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml

images:
  - name: ghcr.io/DevilFlow92/associazione-api
    newTag: dev